### ISSUE TITLE
Problem with iCal export

### ISSUE THREAD

**Issue by TimothyHibbins** [anucssa/anutimetable#122] opened 2022-02-06 22:22 UTC
When exporting to iCal, it exports *all* classes, including the ones I've hidden. I only want the tutorials that I have chosen, otherwise I have to go and manually delete them in my calendar.

**Comment by pl4nty** [comment] 2022-02-07 10:31
Just to clarify, you're using the hide button at the bottom right of specific classes? Unfortunately the export services don't support hidden classes at the moment, but it's definitely something I could add. Note that choosing a tutorial (with the choose button) is still supported though.

**Comment by TimothyHibbins** [comment] 2022-02-07 10:47
Hi Tom,

I believe I did click choose, and it automatically hides the other options.
It’s just that when I exported to iCal it exported everything. If it could
be changed to only export what I have chosen that would be a very useful
addition

Thank you!

**Comment by pl4nty** [comment] 2022-02-07 10:52
Interesting, I tested before commenting and it seemed to work - can you provide your timetable URL?

**Comment by pl4nty** [comment] 2022-02-07 10:53
Actually... We started using an MS Form for issue reporting ages ago. When you clicked "report issues here", did it take you to GitHub?

**Comment by TimothyHibbins** [comment] 2022-02-08 00:03
Hi Tom,

This is my timetable URL: <
https://timetable.cssa.club/?y=2022&s=S1&PHIL2122=&PHIL2061=TutA4&PHIL3073=TutA2&DESN2002=StuA1
>

I have clicked 'choose' on the ones I want and it automatically hides the
others so it looks like this:
[image: Screen Shot 2022-02-08 at 11.00.32 am.png]
 However, this is what I get when I export:
[image: Screen Shot 2022-02-08 at 10.58.37 am.png]
Upon further examining, I think it actually has worked as you said but for
some reason, it is showing a bunch of PHIL2122 Tutorial options on export
which don't show in the main calendar.

With the report button, it did take me to Github but when I clicked it
again now it took me to a Microsoft form.

**Comment by pl4nty** [comment] 2022-02-08 00:45
It looks like you had an older version of the timetable, could you try removing and re-adding PHIL2122 please?

@OliverBalfour almost certain this is a serviceworker bug. possibly the qs parameters are preventing it from detecting and loading a new timetable version? will prioritise cause this is a pretty nasty bug

**Comment by TimothyHibbins** [comment] 2022-02-08 00:49
Unfortunately removing and re-adding did not work.

**Comment by pl4nty** [comment] 2022-02-08 00:57
After removing and re-adding, were you able to select a tutorial and export it? The URL should have `PHIL2122=[yourTute]` instead of `PHIL2122=&`

**Comment by pl4nty** [comment] 2022-02-08 00:57
Like https://timetable.cssa.club/?y=2022&s=S1&PHIL2122=TutA6&PHIL2061=TutA4&PHIL3073=TutA2&DESN2002=StuA1

**Comment by TimothyHibbins** [comment] 2022-02-08 00:59
When I removed and re-added it, it still didn't show any of the PHIL2122
tutorials. It is the same when I click on the link you just sent.
[image: Screen Shot 2022-02-08 at 11.59.09 am.png]

**Comment by pl4nty** [comment] 2022-02-08 01:02
Hmm can you try checking the next week (Feb 27 - Mar 5)? the PHIL2122 tutes don't start until week 2

**Comment by pl4nty** [comment] 2022-02-08 01:02
I can't see your screenshots unfortunately

**Comment by TimothyHibbins** [comment] 2022-02-08 01:05
Ah I didn't realise you can't see the screenshots. And yes it is showing up
for the later weeks now, thank you. As a matter of fact I think there was
no technical issue I'm just not used to needing to go to the next week to
see the tutorials. Thank you!

**Comment by pl4nty** [comment] 2022-02-08 02:03
Good to hear! Once semester starts, the timetable will automatically load the current week (or next week on weekends). But this issue has come up before, I think we discussed some options in #84

**Comment by pl4nty** [comment] 2022-02-08 08:17
I'll close this as a dupe of #84, but noting that we really need to add an FAQ

**Closed by pl4nty** 2022-02-08 08:17 UTC
Labels: bug
