### ISSUE TITLE
google calendar export

### ISSUE THREAD

**Issue by pl4nty** [anucssa/anutimetable#150] opened 2022-02-15 06:55 UTC
calendar exported to google calendar shows all possible options for tutorials/labs/workshops rather than the one selected.

Label: Issue

_Originally submitted by anonymous via the Microsoft Form_

**Comment by OliverBalfour** [comment] 2022-02-15 10:59
Perhaps this is a dupe of #151? It works for me except when there's multiple tutes/labs/workshops

**Closed** 2022-02-22 06:21 UTC
