### ISSUE TITLE
Course IDs not showing up

### ISSUE THREAD

**Issue by pl4nty** [anucssa/anutimetable#142] opened 2022-02-14 00:18 UTC
I previously remember the timetable showing course IDs alongside timings but it doesn't seem to show them anymore. Makes it difficult to figure out which times are for which courses.

Label: Issue

_Originally submitted by anonymous via the Microsoft Form_

**Comment by CraftyDH** [comment] 2022-02-14 03:29
This was a bug which was fixed.

Duplicate of #138

**Closed by CraftyDH** 2022-02-14 03:29 UTC
